# Generated by Django 3.2.16 on 2023-01-17 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms'), ('MISS', 'Miss')], max_length=4)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nhs_number', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=40)),
                ('created_date', models.DateField(null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(null=True)),
                ('urgent', models.CharField(choices=[('NOT URGENT', 'Not Urgent'), ('URGENT', 'Urgent')], max_length=10, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Waiting_Approval'), (1, 'Approved')], default=0)),
                ('doctor', models.CharField(choices=[('DR KEEN', 'Dr Keen'), ('DR PATEL', 'Dr Patel'), ('DR REUBIN', 'Dr Reubin'), ('DR WATSON', 'Dr Watson')], max_length=20)),
                ('admin_decision', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Appointment Model',
                'ordering': ['-created_date'],
            },
        ),
    ]
