# Generated by Django 3.2.16 on 2023-01-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230111_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookappointmentmodel',
            options={'ordering': ['-created_date'], 'verbose_name': 'Book Appointment Model'},
        ),
        migrations.RemoveField(
            model_name='bookappointmentmodel',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='bookappointmentmodel',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='bookappointmentmodel',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookappointmentmodel',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bookappointmentmodel',
            name='nhs_number',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='bookappointmentmodel',
            name='urgent',
            field=models.CharField(choices=[('NOT URGENT', 'Not Urgent'), ('URGENT', 'Urgent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookappointmentmodel',
            name='doctor',
            field=models.CharField(choices=[('DR KEEN', 'Dr Keen'), ('DR PATEL', 'Dr Patel'), ('DR REUBIN', 'Dr Reubin'), ('DR WATSON', 'Dr Watson')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bookappointmentmodel',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms'), ('MISS', 'Miss')], max_length=4),
        ),
    ]
