# Generated by Django 3.2.16 on 2023-01-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_appointments_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='nhs_number',
            field=models.IntegerField(null=True),
        ),
    ]
