# Generated by Django 3.2.16 on 2023-01-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_appointment_nhs_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='STATUS',
            new_name='status',
        ),
    ]
